### ISSUE TITLE
Napari-Storm crashes when uncertainty values are to high

### ISSUE THREAD

**Issue by LREIN663** [napari-storm/napari-storm#19]
The billboard size is set according to the the highest sigma value so in  a dataset with some very bad localisations (sigma > 1000 nm) the program will just crash.

**Comment by napari-storm** [comment]
Ignore the largest 1% of sigma values when calculating the billboard size?

**Comment by LREIN663** [comment]
Implemented with 5613df3ab2f70207a3c2dc2b98e7238a4ef1a1fa
