### ISSUE TITLE
Problem with default install

### ISSUE THREAD

**Issue by cleterrier** [napari-storm/napari-storm#29]
Hi,

Installing following the default method in the readme results in a plugin that miss some functionalities (contrast slider etc.):
![Capture d’écran 2022-03-19 à 12 08 23](https://user-images.githubusercontent.com/1062283/159118638-48d7a268-7750-4426-9d89-d6cc22739a77.jpg)

This is because on my setup (Windows 10), a newly created conda environment uses python 3.10.2 by default (from conda forge). A fully functioning install is obtained by using python=3.9 as argument when creating the environment.

**Comment by LREIN663** [comment]
Thanks alot for your feedback! I managed to recreate the bug and it should be fixed now with 6f9a499e9e2d302b9482fa1e7302e0bb94afa645. Some QSlider methods seem to only accept  integers with the new python version.

**Comment by LREIN663** [comment]
fixed with 6784658aa84b5ca1d163f074e1f7f2792bb914ec
